// src/components/projekt-card.tsx
import { Badge } from '@/components/ui/badge'
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Link } from '@/i18n/navigation'
import type React from 'react'

import { Lens } from '@/components/ui/lens'

export interface ProjectCardProps {
  projektImage: string
  projektImageAlt: string
  projektImageBgColor: string
  projektTitle: string
  projektBadges: string[]
  projektLink: string
  children: React.ReactNode
}

const ProjektCard: React.FC<ProjectCardProps> = ({
  projektImage,
  projektImageAlt,
  projektImageBgColor,
  projektTitle,
  projektBadges,
  projektLink,
  children,
}) => {
  // Check if the link is external (starts with http:// or https://)
  const isExternalLink =
    projektLink?.startsWith('http://') || projektLink?.startsWith('https://')

  const cardContent = (
    <Card className="flex flex-col overflow-hidden border border-border/50 bg-card/50 backdrop-blur-sm hover:bg-card/80 transition-colors cursor-pointer h-full">
      <CardHeader>
        <CardTitle>{projektTitle}</CardTitle>
        <CardDescription>
          <section className="flex flex-wrap gap-2">
            {projektBadges.map((badge) => (
              <Badge key={badge} variant="default">
                {badge}
              </Badge>
            ))}
          </section>
        </CardDescription>
      </CardHeader>
      <CardContent>
        <section className="flex flex-col justify-between gap-4">
          <p>{children}</p>
        </section>
      </CardContent>
      <CardFooter className="flex grow flex-col items-center justify-center gap-4 p-4">
        <section className={`flex items-center justify-center rounded-sm`}>
          <div className="mt-auto flex flex-col px-2">
            <Lens
              zoomFactor={2}
              lensSize={150}
              isStatic={false}
              ariaLabel="Zoom Area"
            >
              <img
                src={projektImage}
                alt={projektImageAlt}
                className={`${projektImageBgColor ? projektImageBgColor : 'bg-background'} w-full p-4 rounded-sm object-contain`}
                //width={480}
                //height={480}
              />
            </Lens>
          </div>
        </section>
      </CardFooter>
    </Card>
  )

  // For external links, use a regular anchor tag
  if (isExternalLink) {
    return (
      <a href={projektLink} target="_blank" rel="noopener noreferrer">
        {cardContent}
      </a>
    )
  }

  // For internal links, use the next-intl Link component
  return <Link href={projektLink}>{cardContent}</Link>
}

export default ProjektCard

// app/components/ProjektCard.vue
<template>
  <component :is="linkComponent" v-bind="linkProps">
    <Card class="bg-card/50 backdrop-blur-sm">
      <CardHeader>
        <CardTitle>{{ projektTitle }}</CardTitle>
        <CardDescription>
          <section class="flex flex-wrap gap-2">
            <Badge v-for="badge in projektBadges" :key="badge" variant="default">
              {{ badge }}
            </Badge>
          </section>
        </CardDescription>
      </CardHeader>
      <CardContent>
        <section class="flex flex-col justify-between gap-4">
          <p><slot /></p>
        </section>
      </CardContent>
      <CardFooter class="flex grow flex-col items-center justify-center gap-4 p-4">
        <section class="flex items-center justify-center rounded-sm">
          <!-- Lens replacement: Just img for now, or find Vue Lens equivalent -->
          <!-- Next.js used @/components/ui/lens. Assuming we can port or skip Lens effect.
               Skipping Lens effect for simplicity for now, just render image. -->
          <img
            :src="projektImage"
            :alt="projektImageAlt"
            :class="[projektImageBgColor ? projektImageBgColor : 'bg-background', 'w-full p-4 rounded-sm object-contain']"
          />
        </section>
      </CardFooter>
    </Card>
  </component>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Badge } from '@/components/ui/badge'
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { NuxtLinkLocale } from '#components'

const props = defineProps<{
  projektImage: string
  projektImageAlt: string
  projektImageBgColor: string
  projektTitle: string
  projektBadges: string[]
  projektLink: string
}>()

const isExternalLink = computed(() => props.projektLink?.startsWith('http://') || props.projektLink?.startsWith('https://'))

const linkComponent = computed(() => isExternalLink.value ? 'a' : NuxtLinkLocale)
const linkProps = computed(() => isExternalLink.value
  ? { href: props.projektLink, target: '_blank', rel: 'noopener noreferrer' }
  : { to: props.projektLink }
)
</script>
