// pages/impressum.vue
<template>
  <main class="flex min-h-screen flex-col items-center justify-between p-4">
    <div class="mt-5 pb-12">
      <div class="mb-2 w-full font-bold text-3xl">Impressum</div>

      <div class="py-2 font-bold text-2xl">Angaben gemäß § 5 TMG:</div>
      <NuxtLink
        to="https://maps.apple.com/?address=Ludwig-Renn-Stra%C3%9Fe%2033,%2012679%20Berlin,%20Deutschland&ll=52.551673,13.558337"
        external
      >
        <div class="py-1 text-lg">
          Aps, Fabian
          <br />
          Ludwig-Renn-Straße 33
          <br />
          12679 Berlin, Deutschland
        </div>
      </NuxtLink>

      <div class="py-2 font-bold text-2xl">Kontakt:</div>
      <div class="py-1 text-lg">
        <div class="flex flex-col items-start">
          <div class="flex flex-row items-center">
            <NuxtLink
              to="mailto:aps.fabian@outlook.com"
              external
            >
              <p class="cursor-context-menu">
                E-Mail: aps.fabian@outlook.com
              </p>
            </NuxtLink>
          </div>
          <div class="flex flex-row items-center">
            <NuxtLink to="tel:+4917645172171" external>
              <p class="cursor-context-menu">
                Telefonnummer: +4917645172171
              </p>
            </NuxtLink>
          </div>
        </div>
      </div>

      <div class="py-2 font-bold text-2xl">
        Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:
      </div>
      <NuxtLink
        to="https://maps.apple.com/?address=Ludwig-Renn-Stra%C3%9Fe%2033,%2012679%20Berlin,%20Deutschland&ll=52.551673,13.558337"
        external
      >
        <div class="py-1 text-lg">
          Aps, Fabian
          <br />
          Ludwig-Renn-Straße 33
          <br />
          12679 Berlin, Deutschland
        </div>
      </NuxtLink>
    </div>
  </main>
</template>

<script setup lang="ts">
</script>

<style>
</style>

// src/app/(pages)/impressum.tsx
import React from 'react';
import { StyleSheet } from 'react-native';
import { ThemedView } from '@/components/ThemedView';
import { ThemedText } from '@/components/ThemedText';
import { ExternalLink } from '@/components/ExternalLink';

export default function Impressum() {
  const emailaddress = 'aps.fabian@outlook.com';
  const phonenumber = '+4917645172171';
  const maintainer = 'Aps, Fabian';

  const Address = () => (
    <ThemedView>
      <ThemedText>{maintainer}</ThemedText>
      <ExternalLink
        href='https://maps.apple.com/?address=Ludwig-Renn-Stra%C3%9Fe%2033,%2012679%20Berlin,%20Deutschland&ll=52.551673,13.558337'
      >
        <ThemedView style={{ flexDirection: 'column' }}>
          <ThemedText>Ludwig-Renn-Straße 33</ThemedText>
          <ThemedText>12679 Berlin</ThemedText>
          <ThemedText>Deutschland</ThemedText>
        </ThemedView>
      </ExternalLink>
    </ThemedView>

  );

  const Contact = () => (
    <ThemedView style={{ flexDirection: 'column' }}>
      <ThemedView style={{ flexDirection: 'row' }}>
        <ThemedText>Telefon: </ThemedText>
        <ExternalLink href={`tel:${phonenumber}`}>
          <ThemedText>{phonenumber}</ThemedText>
        </ExternalLink>
      </ThemedView>
      <ThemedView style={{ flexDirection: 'row' }}>
        <ThemedText>E-Mail: </ThemedText>
        <ExternalLink href={`mailto:${emailaddress}`}>
          <ThemedText>{emailaddress}</ThemedText>
        </ExternalLink>
      </ThemedView>
    </ThemedView>
  );

  return (
    <ThemedView style={styles.container}>
      <ThemedText type='title' style={styles.title}>Impressum</ThemedText>
      <ThemedText type='subtitle' style={styles.subtitle}>Angaben gemäß § 5 TMG:</ThemedText>
      <Address />

      <ThemedText type='subtitle' style={styles.subtitle}>Kontakt:</ThemedText>
      <Contact />

      <ThemedText type='subtitle' style={styles.subtitle}>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:</ThemedText>
      <Address />
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
  },
  title: {
    marginTop: 25,
    marginBottom: 20,
  },
  subtitle: {
    marginTop: 15,
    marginBottom: 10,
  },
});
