// src/app/[locale]/cv/page.tsx
"use client"
import SkillCard, { type SkillCardProps } from "@/components/skill-card";
import {
  TimeLineElementBig,
  TimeLineElementSmall,
  type TimeLineElementProps
} from "@/components/timeline-element";
import MasonryGrid, { Variants } from "@/components/MasonryGrid";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import Timeline from "@mui/lab/Timeline";
import { timelineItemClasses } from "@mui/lab/TimelineItem";
import { useMemo } from "react";
import { useTranslations } from "next-intl";
import {
  GraduationCap,
  Briefcase,
  Wrench,
  Mail,
  Phone,
  MapPin,
  Calendar
} from "lucide-react";
import { contactDetails } from "@/lib/contact";
import Link from "next/link";
import {
  educationItems,
  experienceItems,
  skillItems,
  skillCategories,
  sortByEndDate
} from "@/lib/cv-data";




export default function CVPage() {
  const t = useTranslations();

  // Transform education data with translations
  const education = useMemo(() => {
    const items: (TimeLineElementProps & { key: string })[] = educationItems.map((edu) => ({
      key: edu.key,
      TimeLineTitle: t(edu.nameKey),
      TimeLineBadges: edu.badgeKeys.map((bk) => {
        // Handle dynamic badges with parameters
        if (bk.includes("semester")) return t(bk, { semester: 6 });
        if (bk.includes("years")) return t(bk, { years: 3 });
        return t(bk);
      }),
      TimeLineImage: edu.image,
      TimeLineImageAlt: t(edu.imgAltKey),
      TimeLineImageFallback: edu.imageFallback,
      startdate: edu.startdate,
      enddate: edu.enddate,
      children: t(edu.descriptionKey),
    }));
    return sortByEndDate(items);
  }, [t]);

  // Transform experience data with translations
  const experience = useMemo(() => {
    const items: (TimeLineElementProps & { key: string })[] = experienceItems.map((exp) => ({
      key: exp.key,
      TimeLineTitle: t(exp.nameKey),
      TimeLineBadges: t.raw(exp.badgesKey) as string[],
      TimeLineImage: exp.image,
      TimeLineImageAlt: t(exp.imgAltKey),
      TimeLineImageFallback: exp.imageFallback,
      startdate: exp.startdate,
      enddate: exp.enddate,
      children: t(exp.descriptionKey),
    }));
    return sortByEndDate(items);
  }, [t]);

  // Transform skills data with translations
  const skills = useMemo(() => {
    const items: SkillCardProps[] = skillItems.map((skill) => {
      // Build badges from translation keys and static badges
      const badges: string[] = [
        ...skill.badgeKeys.map((bk) => t(bk)),
        ...(skill.staticBadges || []),
      ];

      // Add experience duration badge if available
      if (skill.experience) {
        const expBadge = t(`Cv.skills.badges.${skill.experience.type}`, { count: skill.experience.count });
        badges.push(expBadge);
      }

      // For screen: use darkImage if available, otherwise use normal image
      // For print: always use the light/normal image
      const screenImage = skill.darkImage || skill.image;
      // Only set print image if there's a dark variant (meaning we need to switch)
      const printImage = skill.darkImage ? skill.image : undefined;

      return {
        SkillTitle: skill.title,
        SkillBadges: badges,
        SkillImage: screenImage,
        SkillImagePrint: printImage,
        SkillImageAlt: skill.imageAlt,
        SkillImageFallback: skill.imageFallback,
        Skilllevel: skill.level,
        category: skill.category,
      };
    });
    return items.sort((a, b) => a.SkillTitle.localeCompare(b.SkillTitle));
  }, [t]);


  return (

    <div className="flex flex-col gap-6 px-4 py-6 mx-auto">
      {/* Header / Personal Info */}
      <Card className="my-glass print:bg-white print:shadow-none">
        <CardHeader className="text-center pb-2">
          <h1 className="text-3xl md:text-4xl font-bold">{t("Aboutme.name")}</h1>
          <p className="text-lg text-muted-foreground">{t("Cv.about.title")}</p>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 print:grid-cols-1 gap-4 text-sm">
            {/* Contact Info */}
            <div className="flex flex-col gap-2">
              <Link
                href={contactDetails.email.link}
                className="flex items-center gap-2 hover:text-primary transition-colors"
              >
                <Mail className="w-4 h-4" />
                {contactDetails.email.display}
              </Link>
              <Link
                href={contactDetails.telephone.link}
                className="flex items-center gap-2 hover:text-primary transition-colors"
              >
                <Phone className="w-4 h-4" />
                {contactDetails.telephone.display}
              </Link>
              <div className="flex items-center gap-2 text-muted-foreground">
                <Calendar className="w-4 h-4" />
                {t("Cv.about.birthday")}: 06.06.2003
              </div>
            </div>
            {/* Address */}
            <a
              href={contactDetails.address.link}
              target="_blank"
              rel="noreferrer"
              className="flex items-start gap-2 hover:text-primary transition-colors"
            >
              <MapPin className="w-4 h-4 mt-0.5 shrink-0" />
              <div>
                {contactDetails.address.street}<br />
                {contactDetails.address.zip} {t(contactDetails.address.city)}, {t(contactDetails.address.country)}
              </div>
            </a>
          </div>
        </CardContent>
      </Card>

      {/* Education Section */}
      <section>
        <h2 className="text-2xl md:text-3xl font-bold text-center flex items-center justify-center gap-2 mb-4">
          <GraduationCap className="w-6 h-6 text-primary print:text-black" />
          {t("Cv.education.title")}
        </h2>

        {/* Large Timeline */}
        <Timeline position="right" className="show-timeline-big">
          {education.map((e) => (
            <TimeLineElementBig
              key={e.key}
              TimeLineTitle={e.TimeLineTitle}
              TimeLineBadges={e.TimeLineBadges}
              TimeLineImage={e.TimeLineImage}
              TimeLineImageAlt={e.TimeLineImageAlt}
              TimeLineImageFallback={e.TimeLineImageFallback}
              startdate={e.startdate}
              enddate={e.enddate}
            >
              <p>{e.children}</p>
            </TimeLineElementBig>
          ))}
        </Timeline>

        {/* Small Timeline */}
        <Timeline
          sx={{
            [`& .${timelineItemClasses.root}:before`]: {
              flex: 0,
              padding: 0,
            },
          }}
          className="show-timeline-small"
        >
          {education.map((e) => (
            <TimeLineElementSmall
              key={e.key}
              TimeLineTitle={e.TimeLineTitle}
              TimeLineBadges={e.TimeLineBadges}
              TimeLineImage={e.TimeLineImage}
              TimeLineImageAlt={e.TimeLineImageAlt}
              TimeLineImageFallback={e.TimeLineImageFallback}
              startdate={e.startdate}
              enddate={e.enddate}
            >
              <p>{e.children}</p>
            </TimeLineElementSmall>
          ))}
        </Timeline>
      </section>

      {/* Experience Section */}
      <section>
        <h2 className="text-2xl md:text-3xl font-bold text-center flex items-center justify-center gap-2 mb-4">
          <Briefcase className="w-6 h-6 text-primary print:text-black" />
          {t("Cv.experience.title")}
        </h2>

        {/* Large Timeline */}
        <Timeline position="right" className="show-timeline-big">
          {experience.map((ex) => (
            <TimeLineElementBig
              key={ex.key}
              TimeLineTitle={ex.TimeLineTitle}
              TimeLineBadges={ex.TimeLineBadges}
              TimeLineImage={ex.TimeLineImage}
              TimeLineImageAlt={ex.TimeLineImageAlt}
              TimeLineImageFallback={ex.TimeLineImageFallback}
              startdate={ex.startdate}
              enddate={ex.enddate}
            >
              <div>{ex.children}</div>
            </TimeLineElementBig>
          ))}
        </Timeline>

        {/* Small Timeline */}
        <Timeline
          sx={{
            [`& .${timelineItemClasses.root}:before`]: {
              flex: 0,
              padding: 0,
            },
          }}
          className="show-timeline-small"
        >
          {experience.map((ex) => (
            <TimeLineElementSmall
              key={ex.key}
              TimeLineTitle={ex.TimeLineTitle}
              TimeLineBadges={ex.TimeLineBadges}
              TimeLineImage={ex.TimeLineImage}
              TimeLineImageAlt={ex.TimeLineImageAlt}
              TimeLineImageFallback={ex.TimeLineImageFallback}
              startdate={ex.startdate}
              enddate={ex.enddate}
            >
              <div>{ex.children}</div>
            </TimeLineElementSmall>
          ))}
        </Timeline>
      </section>

      {/* Skills Section */}
      <section>
        <h2 className="text-2xl md:text-3xl font-bold text-center flex items-center justify-center gap-2 mb-4">
          <Wrench className="w-6 h-6 text-primary print:text-black" />
          {t("Cv.skills.title")}
        </h2>

        <div className="flex flex-col gap-8">
          {skillCategories.map((cat) => {
            const catSkills = skills.filter((s) => s.category === cat.key);
            if (catSkills.length === 0) return null;

            return (
              <div key={cat.key} className="break-inside-avoid">
                <h3 className="text-xl font-semibold mb-4 ml-1 opacity-80">{t(cat.titleKey)}</h3>
                <MasonryGrid variant={Variants.skills}>
                  {catSkills.map((s) => (
                    <SkillCard
                      key={s.SkillTitle}
                      SkillTitle={s.SkillTitle}
                      SkillBadges={s.SkillBadges}
                      SkillImage={s.SkillImage}
                      SkillImagePrint={s.SkillImagePrint}
                      SkillImageAlt={s.SkillImageAlt}
                      SkillImageFallback={s.SkillImageFallback}
                      Skilllevel={s.Skilllevel}
                    />
                  ))}
                </MasonryGrid>
              </div>
            );
          })}
        </div>
      </section>

    </div>
  );
}

// src/routes/[[locale=locale]]/cv/+page.svelte
<script lang="ts">
  import { useIntlayer } from "svelte-intlayer";
  import * as Card from "$lib/components/ui/card";
  import AuroraText from "$lib/components/AuroraText.svelte";
  import TypingAnimation from "$lib/components/TypingAnimation.svelte";
  import MasonryGrid from "$lib/components/MasonryGrid.svelte";
  import * as TimelineCard from "$lib/components/timeline-card";
  import * as SkillCard from "$lib/components/skill-card";
  import { contactDetails } from "$lib/contact";
  import {
    educationItems,
    experienceItems,
    skillItems,
    skillCategories,
    sortByEndDate,
    type SkillItem,
  } from "$lib/cv-data";
  import {
    GraduationCap,
    Briefcase,
    Wrench,
    Mail,
    Phone,
    MapPin,
    User,
    Calendar,
  } from "@lucide/svelte";
  import { Badge } from "$lib/components/ui/badge";
  import { t, tArr } from "$lib/i18n";

  const cv = useIntlayer("cv");
  const aboutme = useIntlayer("aboutme");
  const sites = useIntlayer("sites");

  const sortedEducation = sortByEndDate(educationItems);
  const sortedExperience = sortByEndDate(experienceItems);

  // Group skills by category
  function getSkillsByCategory(cat: string): SkillItem[] {
    return skillItems
      .filter((s) => s.category === cat)
      .sort((a, b) => b.level - a.level);
  }
  function getExperienceLabel(skill: SkillItem): string {
    if (!skill.experience) return "";
    const { type, count } = skill.experience;
    const key = `skills.badges.${type}`;
    const result = t($cv, key, { count });
    return result !== key ? result : `${count} ${type}`;
  }

  // Calculate age
  const today = new Date();
  const birthday = new Date("2003-06-06");
  let age = today.getFullYear() - birthday.getFullYear();
  const mo = today.getMonth() - birthday.getMonth();
  if (mo < 0 || (mo === 0 && today.getDate() < birthday.getDate())) age--;
</script>

<svelte:head>
  <title>{$sites.cv} — {$aboutme.name}</title>
</svelte:head>

<div class="flex flex-col gap-8 px-4 py-6 mx-auto">
  <!-- Personal Info Card -->
  <Card.Root class="my-glass print:bg-white print:shadow-none">
    <Card.Header class="text-center pb-2">
      <h1 class="text-3xl md:text-4xl font-bold">{$aboutme.name}</h1>
      <p class="text-lg text-muted-foreground">{$cv.about.title}</p>
    </Card.Header>
    <Card.Content>
      <div
        class="grid grid-cols-1 md:grid-cols-2 print:grid-cols-1 gap-4 text-sm"
      >
        <!-- Contact Info -->
        <div class="flex flex-col gap-2">
          <a
            href={contactDetails.email.link}
            class="flex items-center gap-2 hover:text-primary transition-colors"
          >
            <Mail class="w-4 h-4" />
            {contactDetails.email.display}
          </a>
          <a
            href={contactDetails.telephone.link}
            class="flex items-center gap-2 hover:text-primary transition-colors"
          >
            <Phone class="w-4 h-4" />
            {contactDetails.telephone.display}
          </a>
          <div class="flex items-center gap-2 text-muted-foreground">
            <Calendar class="w-4 h-4" />
            {$cv.about.birthday}: 06.06.2003
          </div>
        </div>
        <!-- Address -->
        <div class="flex flex-col gap-2">
          <a
            href={contactDetails.address.link}
            target="_blank"
            rel="noreferrer"
            class="flex items-start gap-2 hover:text-primary transition-colors"
          >
            <MapPin class="w-4 h-4 mt-0.5 shrink-0" />
            <div>
              {contactDetails.address.street}<br />
              {contactDetails.address.zip}
              {$cv.about.address.berlin}, {$cv.about.address.germany}
            </div>
          </a>
        </div>
      </div>
    </Card.Content>
  </Card.Root>

  <!-- Education Section -->
  <section class="space-y-4">
    <h2
      class="text-2xl md:text-3xl font-bold text-center flex items-center justify-center gap-2 mb-4"
    >
      <GraduationCap class="w-6 h-6 text-primary print:text-black" />
      {$cv.education.title}
    </h2>

    <!-- Large Timeline (Hidden on small screens) -->
    <div class="hidden sm:flex flex-col w-full mx-auto">
      {#each sortedEducation as item, i}
        <div class="flex flex-row w-full min-h-[100px]">
          <!-- Opposite content (Dates) -->
          <div class="w-[150px] shrink-0 text-right pr-4 pt-[18px]">
            <Badge
              variant="default"
              class="text-[10px] whitespace-nowrap opacity-80 font-normal tracking-wide"
            >
              {item.startdate} - {item.enddate}
            </Badge>
          </div>
          <!-- Separator (Line + Dot) -->
          <div
            class="flex flex-col items-center flex-none relative w-[11px] mx-6"
          >
            <!-- Continuous line -->
            <div
              class="absolute w-[2px] bg-border/50 min-h-[50px] {i === 0
                ? 'top-[24px]'
                : 'top-0'} {i === sortedEducation.length - 1
                ? 'bottom-[calc(100%-30px)]'
                : 'bottom-0'}"
            ></div>
            <div
              class="w-[11px] h-[11px] rounded-full bg-background border-2 border-muted-foreground mt-5 z-10 shadow-sm relative"
            ></div>
          </div>
          <!-- Content (Card) -->
          <div class="flex-1 pl-4 pb-8">
            <TimelineCard.Root
              image={item.image || ""}
              imageAlt={String(t($cv, item.imgAltKey))}
              imageFallback={item.imageFallback}
              title={String(t($cv, item.nameKey))}
              badges={item.badgeKeys.map((k) => {
                if (k.includes("semester"))
                  return String(t($cv, k, { semester: 6 }));
                if (k.includes("years")) return String(t($cv, k, { years: 3 }));
                return String(t($cv, k));
              })}
            >
              <p class="text-sm text-muted-foreground">
                {String(t($cv, item.descriptionKey))}
              </p>
            </TimelineCard.Root>
          </div>
        </div>
      {/each}
    </div>

    <!-- Small Timeline (Visible on small screens) -->
    <div
      class="block sm:hidden relative ml-3 border-l-[2px] border-border/50 pl-6 space-y-8 pb-4"
    >
      {#each sortedEducation as item}
        <div class="relative">
          <div
            class="absolute -left-[calc(1.5rem+6px)] top-5 w-[11px] h-[11px] rounded-full bg-transparent border-2 border-muted-foreground z-10 shadow-sm bg-background"
          ></div>
          <TimelineCard.Root
            image={item.image || ""}
            imageAlt={String(t($cv, item.imgAltKey))}
            imageFallback={item.imageFallback}
            title={String(t($cv, item.nameKey))}
            badges={[
              `${item.startdate} - ${item.enddate}`,
              ...item.badgeKeys.map((k) => {
                if (k.includes("semester"))
                  return String(t($cv, k, { semester: 6 }));
                if (k.includes("years")) return String(t($cv, k, { years: 3 }));
                return String(t($cv, k));
              }),
            ]}
          >
            <p class="text-sm text-muted-foreground">
              {String(t($cv, item.descriptionKey))}
            </p>
          </TimelineCard.Root>
        </div>
      {/each}
    </div>
  </section>

  <!-- Experience Section -->
  <section class="space-y-4">
    <h2
      class="text-2xl md:text-3xl font-bold text-center flex items-center justify-center gap-2 mb-4"
    >
      <Briefcase class="w-6 h-6 text-primary print:text-black" />
      {$cv.experience.title}
    </h2>

    <!-- Large Timeline (Hidden on small screens) -->
    <div class="hidden sm:flex flex-col w-full mx-auto">
      {#each sortedExperience as item, i}
        <div class="flex flex-row w-full min-h-[100px]">
          <!-- Opposite content (Dates) -->
          <div class="w-[150px] shrink-0 text-right pr-4 pt-[18px]">
            <Badge
              variant="default"
              class="text-[10px] whitespace-nowrap opacity-80 font-normal tracking-wide"
            >
              {item.startdate} - {item.enddate}
            </Badge>
          </div>
          <!-- Separator (Line + Dot) -->
          <div
            class="flex flex-col items-center flex-none relative w-[11px] mx-6"
          >
            <!-- Continuous line -->
            <div
              class="absolute w-[2px] bg-border/50 min-h-[50px] {i === 0
                ? 'top-[24px]'
                : 'top-0'} {i === sortedExperience.length - 1
                ? 'bottom-[calc(100%-30px)]'
                : 'bottom-0'}"
            ></div>
            <div
              class="w-[11px] h-[11px] rounded-full bg-background border-2 border-muted-foreground mt-5 z-10 shadow-sm relative"
            ></div>
          </div>
          <!-- Content (Card) -->
          <div class="flex-1 pl-4 pb-8">
            <TimelineCard.Root
              image={item.image || ""}
              imageAlt={String(t($cv, item.imgAltKey))}
              imageFallback={item.imageFallback}
              title={String(t($cv, item.nameKey))}
              badges={String(t($cv, item.badgesKey) ?? "")
                .split(",")
                .map((b) => b.trim())
                .filter(Boolean)}
            >
              <p class="text-sm text-muted-foreground whitespace-pre-line">
                {String(t($cv, item.descriptionKey))}
              </p>
            </TimelineCard.Root>
          </div>
        </div>
      {/each}
    </div>

    <!-- Small Timeline (Visible on small screens) -->
    <div
      class="block sm:hidden relative ml-3 border-l-[2px] border-border/50 pl-6 space-y-8 pb-4"
    >
      {#each sortedExperience as item}
        <div class="relative">
          <div
            class="absolute -left-[calc(1.5rem+6px)] top-5 w-[11px] h-[11px] rounded-full bg-transparent border-2 border-muted-foreground z-10 shadow-sm bg-background"
          ></div>
          <TimelineCard.Root
            image={item.image || ""}
            imageAlt={String(t($cv, item.imgAltKey))}
            imageFallback={item.imageFallback}
            title={String(t($cv, item.nameKey))}
            badges={[
              `${item.startdate} - ${item.enddate}`,
              ...String(t($cv, item.badgesKey) ?? "")
                .split(",")
                .map((b) => b.trim())
                .filter(Boolean),
            ]}
          >
            <p class="text-sm text-muted-foreground whitespace-pre-line">
              {String(t($cv, item.descriptionKey))}
            </p>
          </TimelineCard.Root>
        </div>
      {/each}
    </div>
  </section>

  <!-- Skills Section -->
  <section class="space-y-4">
    <h2
      class="text-2xl md:text-3xl font-bold text-center flex items-center justify-center gap-2 mb-4"
    >
      <Wrench class="w-6 h-6 text-primary print:text-black" />
      {$cv.skills.title}
    </h2>

    <div class="flex flex-col gap-8">
      {#each skillCategories as category}
        {@const skills = getSkillsByCategory(category.key)}
        {#if skills.length > 0}
          <div class="break-inside-avoid">
            <h3 class="text-xl font-semibold mb-4 ml-1 opacity-80">
              {String(t($cv, category.titleKey))}
            </h3>
            <MasonryGrid variant="skills">
              {#each skills as skill}
                <SkillCard.Root
                  image={skill.darkImage || skill.image || ""}
                  imagePrint={skill.darkImage ? skill.image : undefined}
                  imageAlt={String(t($cv, skill.imageAlt))}
                  imageFallback={skill.imageFallback}
                  title={skill.title}
                  level={skill.level}
                  badges={[
                    ...skill.badgeKeys.map((k) => String(t($cv, k))),
                    ...(skill.experience ? [getExperienceLabel(skill)] : []),
                    ...(skill.staticBadges || []),
                  ]}
                  category={skill.category}
                />
              {/each}
            </MasonryGrid>
          </div>
        {/if}
      {/each}
    </div>
  </section>
</div>
