// app/components/LinkCard.vue
<template>
  <a :href="url" target="_blank" rel="noreferrer" class="flex flex-col gap-2">
    <Card class="bg-card/50 backdrop-blur-sm h-full">
      <CardHeader>
        <div class="flex flex-row items-center justify-between gap-1">
          <Avatar>
            <AvatarImage :src="icon" :alt="`${title} Logo`" />
            <AvatarFallback>{{ title }}</AvatarFallback>
          </Avatar>
          <CardTitle>{{ title }}</CardTitle>
        </div>
        <CardDescription>{{ headding }}</CardDescription>
      </CardHeader>
      <CardContent>
        <p>{{ description }}</p>
      </CardContent>
      <slot />
    </Card>
  </a>
</template>

<script setup lang="ts">
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'

defineProps<{
  title: string
  url: string
  icon: string
  headding: string
  description: string
}>()
</script>

// src/lib/components/link-card/link-card.svelte
<script lang="ts">
  import * as Card from '$lib/components/ui/card';

  interface Props {
    title: string;
    description: string;
    heading: string;
    url: string;
    icon: string;
  }

  let { title, description, heading, url, icon }: Props = $props();
</script>

<div class="break-inside-avoid mb-4">
  <a href={url} target="_blank" rel="noopener noreferrer">
    <Card.Root class="my-glass">
      <Card.Header>
        <div class="flex items-center gap-3">
          <img src={icon} alt={title} class="w-8 h-8 rounded" />
          <div>
            <Card.Title class="text-base">{title}</Card.Title>
            <p class="text-sm text-muted-foreground">{heading}</p>
          </div>
        </div>
        <Card.Description>{description}</Card.Description>
      </Card.Header>
    </Card.Root>
  </a>
</div>
