// src/lib/components/timeline-card/timeline-card.svelte
<script lang="ts">
  import * as Card from '$lib/components/ui/card';
  import * as Avatar from '$lib/components/ui/avatar';
  import { Badge } from '$lib/components/ui/badge';

  interface Props {
    image: string;
    imageAlt: string;
    imageFallback: string;
    title: string;
    badges: string[];
    children?: import('svelte').Snippet;
  }

  let { image, imageAlt, imageFallback, title, badges, children }: Props = $props();
</script>

<Card.Root class="my-glass">
  <Card.Header>
    <div class="flex flex-row items-center justify-between gap-1">
      <Avatar.Root>
        <Avatar.Image src={image} alt={imageAlt} />
        <Avatar.Fallback>{imageFallback}</Avatar.Fallback>
      </Avatar.Root>
      <Card.Title>{title}</Card.Title>
    </div>
    <Card.Description>
      <span class="flex flex-wrap gap-2">
        {#each badges as badge}
          <Badge variant="default">{badge}</Badge>
        {/each}
      </span>
    </Card.Description>
  </Card.Header>
  <Card.Content>
    {#if children}
      {@render children()}
    {/if}
  </Card.Content>
</Card.Root>

// components/TimelineCard.vue
<template>
  <div>
    <Card class="bg-transparent backdrop-blur-sm">
    <CardHeader>
      <div class="flex flex-row items-center justify-between gap-1">
        <Avatar>
          <AvatarImage :src="image" :alt="imageAlt" />
          <AvatarFallback>{{ imageFallback }}</AvatarFallback>
        </Avatar>
        <CardTitle>{{ title }}</CardTitle>
      </div>
      <CardDescription>
        <div class="flex flex-wrap gap-2">
          <Badge variant='default'>{{`${from} – ${to}`}}</Badge>
          <Badge v-for="(badge, index) in badges" :key="index" variant="default">
            {{ badge }}
          </Badge>
        </div>
      </CardDescription>
    </CardHeader>
    <CardContent>
      <slot />
    </CardContent>
  </Card>
  </div>
</template>

<script lang="ts" setup>
import { Badge } from '@/components/ui/badge';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';

interface Props {
  from: string;
  to: string;
  image: string;
  imageAlt: string;
  imageFallback: string;
  title: string;
  badges: string[];
}
const props = defineProps<Props>();

</script>

<style>

</style>
