// components/SideBarToggle.vue
<template>
  <SidebarTrigger
        class="h-[1.2rem] w-[1.2rem] rounded-full bg-transparent backdrop-blur-sm"
        variant="outline"
        size="icon"
      />
      <!--span-- class="sr-only">Toggle Sidebar</!--span-->
</template>

<script lang="ts" setup>
import { SidebarTrigger } from "@/components/ui/sidebar";
</script>

<style>
</style>

// src/components/sidebar-toggle.tsx
"use client";
import { Button } from "@/components/ui/button";
import { SidebarTrigger } from "./ui/sidebar";

export function SidebarToggle() {

  return (
    <Button
      className="rounded-full bg-transparent backdrop-blur-sm"
      variant="outline"
      size="icon"
    >
      <SidebarTrigger />
      <span className="sr-only">Toggle Sidebar</span>
    </Button>
  );
}
