// app/components/UserAvatar.vue
<template>
  <Avatar>
    <AvatarImage :src="computedImage.src" :alt="computedImage.alt" />
    <AvatarFallback>{{ computedImageFallback }}</AvatarFallback>
  </Avatar>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'

export interface ImageProps {
  src: string;
  alt: string;
}

const props = defineProps<{
  name: string;
  githubUserName: string;
  href?: string;
  image?: ImageProps;
  imageFallback?: string;
}>()

function getInitials(str: string): string {
  const words = str.split(" ").filter((word) => word.length > 0)
  const initials = words.map((word) => word.charAt(0))
  return initials.join("")
}

const computedImage = computed(() => {
  if (props.image) return props.image
  return {
    src: `https://github.com/${props.githubUserName}.png`,
    alt: props.name,
  }
})

const computedImageFallback = computed(() => {
  if (props.imageFallback) return props.imageFallback
  return getInitials(props.name)
})
</script>

// src/components/userAvatar.tsx
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import React from "react";

export interface ImageProps {
  src: string;
  alt: string;
}

export interface UserAvatarProps {
  name: string;
  githubUserName: string;
  href?: string;
  image?: ImageProps;
  imageFallback?: string;
}

function getInitials(str: string): string {
  // Split the string into words, filtering out empty strings
  const words = str.split(" ").filter((word) => word.length > 0);

  // Extract the first letter of each word
  const initials = words.map((word) => word.charAt(0));

  // Join the initials into a single string
  return initials.join("");
}

const UserAvatar: React.FC<UserAvatarProps> = ({
  name,
  githubUserName,
  image,
  imageFallback,
}) => {
  if (!image) {
    image = {
      src: `https://github.com/${githubUserName}.png`,
      alt: name,
    };
  }

  if (!imageFallback) {
    imageFallback = getInitials(name);
  }

  return (
    <Avatar>
      <AvatarImage src={image?.src} alt={image?.alt} />
      <AvatarFallback>{imageFallback}</AvatarFallback>
    </Avatar>
  );
};

export default UserAvatar;
