// app/components/AppSidebar.vue
<template>
  <Sidebar
    collapsible="offcanvas"
    class="no-print backdrop-blur-sm rounded-sm"
    v-bind="$attrs"
  >
    <SidebarHeader>
      <SidebarGroup>
        <SidebarGroupContent>
          <SidebarMenu>
            <SidebarMenuItem>
              <Tooltip>
                <TooltipTrigger as-child>
                  <NuxtLinkLocale
                    to="/"
                    class="h-auto py-2 justify-start ring-sidebar-ring hover:bg-sidebar-accent hover:text-sidebar-accent-foreground active:bg-sidebar-accent active:text-sidebar-accent-foreground gap-2 rounded-[calc(var(--radius-sm)+2px)] p-2 text-left text-xs transition-[width,height,padding] group-data-[collapsible=icon]:size-8! group-data-[collapsible=icon]:p-2! focus-visible:ring-2 flex w-full items-center overflow-hidden outline-hidden"
                  >
                    <UserAvatar
                      :name="name"
                      :githubUserName="githubUserName"
                      :image="image"
                      :imageFallback="imageFallback"
                    />
                    <TypingAnimation
                      :typeSpeed="145"
                      :pauseDelay="1450"
                      :deleteSpeed="75"
                      showCursor
                      blinkCursor
                      loop
                      startOnView
                      cursorStyle="underscore"
                      class="group-data-[collapsible=icon]:hidden"
                    >
                      {{ name }}
                    </TypingAnimation>
                  </NuxtLinkLocale>
                </TooltipTrigger>
                <TooltipContent side="right">{{ name }}</TooltipContent>
              </Tooltip>
            </SidebarMenuItem>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>
    </SidebarHeader>

    <SidebarContent>
      <!-- Navigation -->
      <SidebarGroup>
        <SidebarGroupLabel>{{ t("Footer.navigation") }}</SidebarGroupLabel>
        <SidebarGroupContent>
          <SidebarMenu>
             <SidebarMenuItem v-for="item in navigationLinks" :key="item.url">
                <Tooltip>
                  <TooltipTrigger as-child>
                     <NuxtLinkLocale
                        :to="item.url"
                        class="ring-sidebar-ring hover:bg-sidebar-accent hover:text-sidebar-accent-foreground active:bg-sidebar-accent active:text-sidebar-accent-foreground gap-2 rounded-[calc(var(--radius-sm)+2px)] p-2 text-left text-xs transition-[width,height,padding] group-data-[collapsible=icon]:size-8! group-data-[collapsible=icon]:p-2! focus-visible:ring-2 flex w-full items-center overflow-hidden outline-hidden [&>span:last-child]:truncate [&_svg]:size-4 [&_svg]:shrink-0"
                     >
                        <component :is="item.icon" />
                        <span class="group-data-[collapsible=icon]:hidden">
                          {{ item.title }}
                        </span>
                        <Dot
                          v-if="isActive(item.url) || (item.url2 && isActive(item.url2))"
                          class="text-primary"
                          :size="72"
                          :stroke-width="6"
                        />
                     </NuxtLinkLocale>
                  </TooltipTrigger>
                  <TooltipContent side="right">{{ item.title }}</TooltipContent>
                </Tooltip>
             </SidebarMenuItem>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>

      <!-- Connect -->
      <SidebarGroup>
        <SidebarGroupLabel>{{ t("Footer.connect") }}</SidebarGroupLabel>
        <SidebarGroupContent>
          <SidebarMenu>
            <SidebarMenuItem v-for="item in connectLinks" :key="item.url">
               <Tooltip>
                  <TooltipTrigger as-child>
                     <NuxtLinkLocale
                        :to="item.url"
                        class="ring-sidebar-ring hover:bg-sidebar-accent hover:text-sidebar-accent-foreground active:bg-sidebar-accent active:text-sidebar-accent-foreground gap-2 rounded-[calc(var(--radius-sm)+2px)] p-2 text-left text-xs transition-[width,height,padding] group-data-[collapsible=icon]:size-8! group-data-[collapsible=icon]:p-2! focus-visible:ring-2 flex w-full items-center overflow-hidden outline-hidden [&>span:last-child]:truncate [&_svg]:size-4 [&_svg]:shrink-0"
                     >
                        <component :is="item.icon" />
                        <span class="group-data-[collapsible=icon]:hidden">
                          {{ item.title }}
                        </span>
                        <Dot
                          v-if="isActive(item.url)"
                          class="text-primary"
                          :size="72"
                          :stroke-width="6"
                        />
                     </NuxtLinkLocale>
                  </TooltipTrigger>
                  <TooltipContent side="right">{{ item.title }}</TooltipContent>
               </Tooltip>
            </SidebarMenuItem>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>

      <!-- Legal -->
      <SidebarGroup>
        <SidebarGroupLabel>{{ t("Footer.legal") }}</SidebarGroupLabel>
        <SidebarGroupContent>
          <SidebarMenu>
            <SidebarMenuItem v-for="item in legalLinks" :key="item.url">
               <Tooltip>
                  <TooltipTrigger as-child>
                     <NuxtLinkLocale
                        :to="item.url"
                        class="ring-sidebar-ring hover:bg-sidebar-accent hover:text-sidebar-accent-foreground active:bg-sidebar-accent active:text-sidebar-accent-foreground gap-2 rounded-[calc(var(--radius-sm)+2px)] p-2 text-left text-xs transition-[width,height,padding] group-data-[collapsible=icon]:size-8! group-data-[collapsible=icon]:p-2! focus-visible:ring-2 flex w-full items-center overflow-hidden outline-hidden [&>span:last-child]:truncate [&_svg]:size-4 [&_svg]:shrink-0"
                     >
                        <component :is="item.icon" />
                        <span class="group-data-[collapsible=icon]:hidden">
                          {{ item.title }}
                        </span>
                         <Dot
                          v-if="isActive(item.url)"
                          class="text-primary"
                          :size="72"
                          :stroke-width="6"
                        />
                     </NuxtLinkLocale>
                  </TooltipTrigger>
                  <TooltipContent side="right">{{ item.title }}</TooltipContent>
               </Tooltip>
            </SidebarMenuItem>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>
    </SidebarContent>

    <SidebarFooter>
      <SidebarGroup>
        <SidebarGroupLabel class="group-data-[collapsible=icon]:hidden">
          &copy; {{ new Date().getFullYear() }} {{ t("Aboutme.name") }}
        </SidebarGroupLabel>
        <SidebarGroupContent>
          <SidebarMenu>
            <SidebarMenuItem>
              <Langswitcher sidebar />
            </SidebarMenuItem>
            <SidebarMenuItem>
              <SidebarToggle />
            </SidebarMenuItem>
            <!-- Dev Only Link (optional) -->
             <SidebarMenuItem v-if="isDev">
                <SidebarMenuButton as-child>
                   <a
                      href="https://idx.google.com/import?url=https%3A%2F%2Fgithub.com%2FmcpeapsUnterstrichHD%2FmcpeapsUnterstrichHD"
                      target="_blank"
                      rel="noreferrer"
                   >
                    <img
                        height="32"
                        width="32"
                        alt="Open in IDX"
                        src="https://cdn.idx.dev/btn/open_purple_32.svg"
                    />
                   </a>
                </SidebarMenuButton>
             </SidebarMenuItem>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>
    </SidebarFooter>
    <SidebarRail />
  </Sidebar>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarRail,
  SidebarSeparator,
} from '@/components/ui/sidebar'
import UserAvatar, { type ImageProps } from '@/components/UserAvatar.vue' // Adjust import if renamed
// import { Link, usePathname } from '@/i18n/navigation' // Nuxt uses useRoute/NuxtLinkLocale
import { useI18n } from 'vue-i18n'
import TypingAnimation from '@/components/ui/TypingAnimation.vue'
import Langswitcher from '@/components/Langswitcher.vue'
import {
  Home,
  User,
  FolderKanban,
  FileText,
  Mail,
  Link as LinkIcon,
  Scale,
  Dot,
} from 'lucide-vue-next'
import SidebarToggle from '@/components/SidebarToggle.vue'

const { t } = useI18n()
const route = useRoute()
const localePath = useLocalePath()
// Helper to check active route.
// Note: route.path includes locale in Nuxt i18n if strategy is prefix.
// localePath returns the localized path.
const isActive = (url: string) => {
    // If url is root "/", strictly match.
    // Otherwise check startsWith.
    // Better: use exact match or smart match.
    // Nuxt router link active class handles styling usually, but we need the Dot icon condition.
    const path = localePath(url)
    if (url === '/' || url === '') return route.path === path
    return route.path.startsWith(path) && (route.path === path || route.path.charAt(path.length) === '/')
    // Actually, simple strict match might be enough if not nested.
    // Let's rely on strict match if it worked in Next.js.
    // Next.js: pathname === item.url
}
const isDev = import.meta.dev

const navigationLinks = computed(() => [
  { title: t("Sites.root"), url: "/", icon: Home },
  { title: t("Sites.aboutme"), url: "/aboutme", icon: User },
  { title: t("Sites.projects"), url: "/projects", icon: FolderKanban },
  { title: t("Sites.cv"), url: "/cv", url2: "/cv/ats", icon: FileText },
])

const connectLinks = computed(() => [
  { title: t("Sites.contact"), url: "/contact", icon: Mail },
  { title: t("Sites.linkhub"), url: "/linkhub", icon: LinkIcon },
])

const legalLinks = computed(() => [
  { title: t("Sites.impressum"), url: "/imprint", icon: Scale },
])

const name = computed(() => t("Aboutme.name"))
const githubUserName = "mcpeapsUnterstrichHD"
const image = computed<ImageProps>(() => ({
  src: "/pictures/logo.png",
  alt: t("Logo.alt"),
}))
const imageFallback = "MAHD"

</script>

// src/lib/components/AppSidebar.svelte
<script lang="ts">
  import { page } from "$app/state";
  import * as Sidebar from "$lib/components/ui/sidebar";
  import * as Tooltip from "$lib/components/ui/tooltip";
  import UserAvatar from "$lib/components/UserAvatar.svelte";
  import TypingAnimation from "$lib/components/TypingAnimation.svelte";
  import Langswitcher from "$lib/components/Langswitcher.svelte";
  import SidebarToggle from "$lib/components/SidebarToggle.svelte";
  import {
    House,
    User,
    FolderKanban,
    FileText,
    Mail,
    Link as LinkIcon,
    Scale,
    Dot,
    type IconProps,
  } from "@lucide/svelte";
  import { useIntlayer, useLocale } from "svelte-intlayer";
  import { getLocalizedUrl, type Locale } from "intlayer";
  import LocalizedLink from "$lib/components/LocalizedLink.svelte";
  import { t } from "$lib/i18n";

  const footer = useIntlayer("footer");
  const sites = useIntlayer("sites");
  const aboutme = useIntlayer("aboutme");
  const logo = useIntlayer("logo");

  const { locale } = useLocale();

  interface SidebarLink {
    title: string;
    url: string;
    url2?: string;
    icon: any;
  }

  const today = new Date();

  let navigationLinks: SidebarLink[] = $derived([
    { title: t($sites, "root"), url: "/", icon: House },
    { title: t($sites, "aboutme"), url: "/aboutme/", icon: User },
    { title: t($sites, "projects"), url: "/projects/", icon: FolderKanban },
    { title: t($sites, "cv"), url: "/cv/", url2: "/cv/ats/", icon: FileText },
  ]);

  let connectLinks: SidebarLink[] = $derived([
    { title: t($sites, "contact"), url: "/contact/", icon: Mail },
    { title: t($sites, "linkhub"), url: "/linkhub/", icon: LinkIcon },
  ]);

  let legalLinks: SidebarLink[] = $derived([
    { title: t($sites, "impressum"), url: "/imprint/", icon: Scale },
  ]);

  function isActive(itemUrl: string, itemUrl2?: string): boolean {
    const currentLoc = $locale as Locale;
    const path = page.url.pathname.replace(/\/$/, "") || "/";
    const localized1 =
      getLocalizedUrl(itemUrl, currentLoc).replace(/\/$/, "") || "/";
    const localized2 = itemUrl2
      ? getLocalizedUrl(itemUrl2, currentLoc).replace(/\/$/, "") || "/"
      : undefined;
    return path === localized1 || (!!localized2 && path === localized2);
  }
</script>

<Sidebar.Root
  collapsible="offcanvas"
  variant="floating"
  class="no-print my-glass rounded-sm"
>
  <Sidebar.Header>
    <Sidebar.Group>
      <Sidebar.GroupContent>
        <Sidebar.Menu>
          <Sidebar.MenuItem>
            <Tooltip.Root>
              <Tooltip.Trigger
                onclick={() => {}}
                class="flex w-full items-center gap-2 rounded-md p-2 text-left text-xs hover:bg-sidebar-accent hover:text-sidebar-accent-foreground transition-colors overflow-hidden"
              >
                <LocalizedLink
                  href="/"
                  class="flex w-full items-center gap-2 overflow-hidden"
                >
                  <UserAvatar
                    name={t($aboutme, "name")}
                    githubUserName="mcpeapsUnterstrichHD"
                    image={{ src: "/pictures/logo.png", alt: t($logo, "alt") }}
                    imageFallback="MAHD"
                    class="h-8 w-8 rounded-sm"
                  />
                  <span class="group-data-[collapsible=icon]:hidden">
                    <TypingAnimation
                      text={t($aboutme, "name")}
                      typeSpeed={145}
                      pauseDelay={1450}
                      deleteSpeed={75}
                      showCursor
                      blinkCursor
                      loop
                      startOnView
                      cursorStyle="underscore"
                    />
                  </span>
                </LocalizedLink>
              </Tooltip.Trigger>
              <Tooltip.Content side="right"
                >{t($aboutme, "name")}</Tooltip.Content
              >
            </Tooltip.Root>
          </Sidebar.MenuItem>
        </Sidebar.Menu>
      </Sidebar.GroupContent>
    </Sidebar.Group>
  </Sidebar.Header>

  <Sidebar.Content>
    <!-- Navigation -->
    <Sidebar.Group>
      <Sidebar.GroupLabel>{t($footer, "navigation")}</Sidebar.GroupLabel>
      <Sidebar.GroupContent>
        <Sidebar.Menu>
          {#each navigationLinks as item}
            <Sidebar.MenuItem>
              <Sidebar.MenuButton>
                {#snippet child({ props })}
                  <LocalizedLink href={item.url} {...props}>
                    {@const Icon = item.icon}
                    <Icon title={item.title} />
                    <span
                      class="flex-1 truncate group-data-[collapsible=icon]:hidden"
                      >{item.title}</span
                    >
                    {#if isActive(item.url, item.url2)}
                      <Dot
                        class="text-primary shrink-0"
                        size={72}
                        strokeWidth={6}
                      />
                    {/if}
                  </LocalizedLink>
                {/snippet}
              </Sidebar.MenuButton>
            </Sidebar.MenuItem>
          {/each}
        </Sidebar.Menu>
      </Sidebar.GroupContent>
    </Sidebar.Group>

    <!-- Connect -->
    <Sidebar.Group>
      <Sidebar.GroupLabel>{t($footer, "connect")}</Sidebar.GroupLabel>
      <Sidebar.GroupContent>
        <Sidebar.Menu>
          {#each connectLinks as item}
            <Sidebar.MenuItem>
              <Sidebar.MenuButton>
                {#snippet child({ props })}
                  <LocalizedLink href={item.url} {...props}>
                    {@const Icon = item.icon}
                    <Icon title={item.title} />
                    <span
                      class="flex-1 truncate group-data-[collapsible=icon]:hidden"
                      >{item.title}</span
                    >
                    {#if isActive(item.url)}
                      <Dot
                        class="text-primary shrink-0"
                        size={72}
                        strokeWidth={6}
                      />
                    {/if}
                  </LocalizedLink>
                {/snippet}
              </Sidebar.MenuButton>
            </Sidebar.MenuItem>
          {/each}
        </Sidebar.Menu>
      </Sidebar.GroupContent>
    </Sidebar.Group>

    <!-- Legal -->
    <Sidebar.Group>
      <Sidebar.GroupLabel>{t($footer, "legal")}</Sidebar.GroupLabel>
      <Sidebar.GroupContent>
        <Sidebar.Menu>
          {#each legalLinks as item}
            <Sidebar.MenuItem>
              <Sidebar.MenuButton>
                {#snippet child({ props })}
                  <LocalizedLink href={item.url} {...props}>
                    {@const Icon = item.icon}
                    <Icon title={item.title} />
                    <span
                      class="flex-1 truncate group-data-[collapsible=icon]:hidden"
                      >{item.title}</span
                    >
                    {#if isActive(item.url)}
                      <Dot
                        class="text-primary shrink-0"
                        size={72}
                        strokeWidth={6}
                      />
                    {/if}
                  </LocalizedLink>
                {/snippet}
              </Sidebar.MenuButton>
            </Sidebar.MenuItem>
          {/each}
        </Sidebar.Menu>
      </Sidebar.GroupContent>
    </Sidebar.Group>
  </Sidebar.Content>

  <Sidebar.Footer>
    <Sidebar.Group>
      <Sidebar.GroupLabel class="group-data-[collapsible=icon]:hidden">
        &copy; {today.getFullYear()}
        {t($aboutme, "name")}
      </Sidebar.GroupLabel>
      <Sidebar.GroupContent>
        <Sidebar.Menu>
          <Sidebar.MenuItem>
            <Langswitcher sidebar />
          </Sidebar.MenuItem>
          <Sidebar.MenuItem>
            <SidebarToggle />
          </Sidebar.MenuItem>
        </Sidebar.Menu>
      </Sidebar.GroupContent>
    </Sidebar.Group>
  </Sidebar.Footer>

  <Sidebar.Rail />
</Sidebar.Root>
